### ISSUE TITLE
`use-plan` rule

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/eslint-plugin-ava#33] opened 2016-03-03 12:46 UTC
Rule proposal: Enforce the use of `t.plan(n)` in tests.

### Bad
```js
test(t => {
  const bar = foo();
  t.is(bar.a, 1);
  t.is(bar.a, 2);
});
```

### Good
```js
test(t => {
  t.plan(2);

  const bar = foo();
  t.is(bar.a, 1);
  t.is(bar.a, 2);
});
```

**Comment by sindresorhus** [comment] 2016-03-03 14:19
Same as https://github.com/sindresorhus/eslint-plugin-ava/issues/34#issuecomment-191779946.

**Comment by jamestalmage** [comment] 2016-04-01 20:25
Seems like a duplicate of #34. Feel free to reopen if you disagree.

**Closed by jamestalmage** 2016-04-01 20:25 UTC
Labels: enhancement
